version: '2'
services:
    opentradingsystem-app:
        image: opentradingsystem
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://opentradingsystem-mysql:3306/opentradingsystem?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    opentradingsystem-mysql:
        extends:
            file: mysql.yml
            service: opentradingsystem-mysql
